# Generated by Django 6.0.1 on 2026-01-29 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "filters",
                    models.JSONField(default=dict, verbose_name="Критерии фильтрации"),
                ),
                (
                    "columns",
                    models.JSONField(default=list, verbose_name="Видимые колонки"),
                ),
                (
                    "sort_by",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Сортировка по"
                    ),
                ),
                (
                    "sort_order",
                    models.CharField(
                        choices=[("asc", "По возрастанию"), ("desc", "По убыванию")],
                        default="asc",
                        max_length=4,
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="Доступен команде"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохранённый фильтр",
                "verbose_name_plural": "Сохранённые фильтры",
                "ordering": ["-created_at"],
            },
        ),
    ]
