# Generated by Django 6.0.1 on 2026-01-27 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "board_type",
                    models.CharField(
                        choices=[("kanban", "Kanban"), ("scrum", "Scrum")],
                        default="kanban",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Упорядоченный список UUID статусов",
                        verbose_name="Колонки",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Фильтры по типам задач, исполнителям и т.д.",
                        verbose_name="Фильтры",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Настройки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доска",
                "verbose_name_plural": "Доски",
                "ordering": ["name"],
            },
        ),
    ]
