# Generated by Django 6.0.1 on 2026-01-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        ("sprints", "0001_add_sprint_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Активный спринт для Scrum-доски",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boards",
                to="sprints.sprint",
                verbose_name="Спринт",
            ),
        ),
    ]
