# Generated by Django 6.0.1 on 2026-01-27 18:47

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSprint",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("goal", models.TextField(blank=True, verbose_name="Цель спринта")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("active", "Активен"),
                            ("completed", "Завершён"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "initial_story_points",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="SP на старте"
                    ),
                ),
                (
                    "completed_story_points",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="SP завершённых"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Обновлён"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Спринт",
                "verbose_name_plural": "historical Спринты",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("goal", models.TextField(blank=True, verbose_name="Цель спринта")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("active", "Активен"),
                            ("completed", "Завершён"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "initial_story_points",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="SP на старте"
                    ),
                ),
                (
                    "completed_story_points",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="SP завершённых"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спринт",
                "verbose_name_plural": "Спринты",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="sprints_spr_project_816d9a_idx",
                    ),
                    models.Index(
                        fields=["project", "start_date"],
                        name="sprints_spr_project_7d8608_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lt", models.F("end_date"))),
                        name="sprint_dates_valid",
                    )
                ],
            },
        ),
    ]
