# Generated by Django 6.0.1 on 2026-01-29 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notify_on_assign",
                    models.BooleanField(default=True, verbose_name="При назначении"),
                ),
                (
                    "notify_on_mention",
                    models.BooleanField(default=True, verbose_name="При упоминании"),
                ),
                (
                    "notify_on_comment",
                    models.BooleanField(default=True, verbose_name="При комментарии"),
                ),
                (
                    "notify_on_status_change",
                    models.BooleanField(
                        default=False, verbose_name="При смене статуса"
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Мгновенно"),
                            ("daily", "Ежедневный дайджест"),
                            ("weekly", "Еженедельный дайджест"),
                        ],
                        default="instant",
                        max_length=10,
                        verbose_name="Частота уведомлений",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
    ]
