# Generated by Django 6.0.1 on 2026-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="CTrack",
                        max_length=255,
                        verbose_name="Название организации",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="ru", max_length=10, verbose_name="Язык по умолчанию"
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить регистрацию"
                    ),
                ),
                (
                    "smtp_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Настройки SMTP"
                    ),
                ),
                (
                    "storage_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Настройки хранилища"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Системные настройки",
                "verbose_name_plural": "Системные настройки",
            },
        ),
    ]
