# Generated by Django 6.0.1 on 2026-01-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
        ("sprints", "0001_add_sprint_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sprints.sprint",
                verbose_name="Спринт",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="sprints.sprint",
                verbose_name="Спринт",
            ),
        ),
    ]
