# Generated by Django 6.0.1 on 2026-01-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_add_sprint_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Эпик, к которому относится задача",
                limit_choices_to={"issue_type__is_epic": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="issues.issue",
                verbose_name="Эпик",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                help_text="Эпик, к которому относится задача",
                limit_choices_to={"issue_type__is_epic": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="epic_issues",
                to="issues.issue",
                verbose_name="Эпик",
            ),
        ),
        migrations.AddField(
            model_name="issuetype",
            name="is_epic",
            field=models.BooleanField(
                default=False,
                help_text="Эпики группируют связанные задачи",
                verbose_name="Эпик",
            ),
        ),
    ]
