# Generated by Django 6.0.1 on 2026-01-29 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_add_epic_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("updated", "Обновлена"),
                            ("status_changed", "Изменён статус"),
                            ("assigned", "Назначен исполнитель"),
                            ("commented", "Добавлен комментарий"),
                            ("sprint_changed", "Изменён спринт"),
                            ("type_changed", "Изменён тип"),
                            ("priority_changed", "Изменён приоритет"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Поле"),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Старое значение"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Новое значение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="issues.issue",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активность задачи",
                "verbose_name_plural": "Активность задач",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["issue", "-created_at"],
                        name="issues_issu_issue_i_989529_idx",
                    )
                ],
            },
        ),
    ]
