# Generated by Django 6.0.1 on 2026-01-29 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_add_issue_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/", verbose_name="Файл"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Размер (байт)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="MIME-тип"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="issues.issue",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
                "ordering": ["-created_at"],
            },
        ),
    ]
