# Generated by Django 6.0.1 on 2026-01-29 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_add_issueattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueactivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("updated", "Обновлена"),
                    ("status_changed", "Изменён статус"),
                    ("assigned", "Назначен исполнитель"),
                    ("unassigned", "Снят исполнитель"),
                    ("commented", "Добавлен комментарий"),
                    ("sprint_changed", "Изменён спринт"),
                    ("type_changed", "Изменён тип"),
                    ("priority_changed", "Изменён приоритет"),
                    ("due_date_changed", "Изменён срок"),
                    ("story_points_changed", "Изменены Story Points"),
                    ("attachment_added", "Добавлено вложение"),
                    ("attachment_removed", "Удалено вложение"),
                ],
                max_length=20,
                verbose_name="Действие",
            ),
        ),
        migrations.AddIndex(
            model_name="issueactivity",
            index=models.Index(
                fields=["-created_at"], name="issues_issu_created_6ee7f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueactivity",
            index=models.Index(
                fields=["user", "created_at"], name="issues_issu_user_id_8e1d6b_idx"
            ),
        ),
    ]
