# Generated by Django 6.0.1 on 2026-01-30

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_add_activity_types_and_indexes"),
    ]

    operations = [
        # Add SearchVectorField to Issue
        migrations.AddField(
            model_name="issue",
            name="search_vector",
            field=SearchVectorField(null=True, verbose_name="Поисковый вектор"),
        ),
        # Add SearchVectorField to HistoricalIssue (simple_history)
        migrations.AddField(
            model_name="historicalissue",
            name="search_vector",
            field=SearchVectorField(null=True, verbose_name="Поисковый вектор"),
        ),
        # Add additional indexes for Issue
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "sprint"], name="issues_issu_project_bcc24d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["created_at"], name="issues_issu_created_6f38eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["updated_at"], name="issues_issu_updated_f60a88_idx"
            ),
        ),
        # Add GIN index for fast full-text search
        migrations.AddIndex(
            model_name="issue",
            index=GinIndex(fields=["search_vector"], name="issue_search_idx"),
        ),
        # Create trigger function for auto-updating search_vector
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION issue_search_vector_update() RETURNS trigger AS $$
            BEGIN
              NEW.search_vector :=
                setweight(to_tsvector('russian', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('russian', coalesce(NEW.description, '')), 'B') ||
                setweight(to_tsvector('simple', coalesce(NEW.key, '')), 'A');
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER issue_search_vector_trigger
            BEFORE INSERT OR UPDATE ON issues_issue
            FOR EACH ROW EXECUTE FUNCTION issue_search_vector_update();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS issue_search_vector_trigger ON issues_issue;
            DROP FUNCTION IF EXISTS issue_search_vector_update();
            """,
        ),
        # Update existing records with search vectors
        migrations.RunSQL(
            sql="""
            UPDATE issues_issue SET search_vector =
              setweight(to_tsvector('russian', coalesce(title, '')), 'A') ||
              setweight(to_tsvector('russian', coalesce(description, '')), 'B') ||
              setweight(to_tsvector('simple', coalesce(key, '')), 'A');
            """,
            reverse_sql="UPDATE issues_issue SET search_vector = NULL;",
        ),
    ]
