# Generated by Django 6.0.1 on 2026-01-29 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_add_saved_filter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "field_key",
                    models.CharField(
                        help_text="Ключ для JSONB (например, cf_priority)",
                        max_length=50,
                        verbose_name="Ключ поля",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("textarea", "Многострочный текст"),
                            ("number", "Число"),
                            ("date", "Дата"),
                            ("datetime", "Дата и время"),
                            ("checkbox", "Флажок"),
                            ("select", "Выбор"),
                            ("multiselect", "Множественный выбор"),
                            ("user", "Пользователь"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип поля",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Для типов select/multiselect",
                        verbose_name="Варианты выбора",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Обязательное"),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Значение по умолчанию"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "applicable_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UUID типов задач, к которым применяется поле",
                        verbose_name="Применимые типы задач",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто = глобальное поле",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Определение кастомного поля",
                "verbose_name_plural": "Определения кастомных полей",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "field_key"],
                        name="custom_fiel_project_213475_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "field_key"),
                        name="unique_field_key_per_project",
                    )
                ],
            },
        ),
    ]
